export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

export const RESET_SUCCESS = 'SIGNOUT_SUCCESS';
export const RESET_ERROR = 'SIGNOUT_ERROR';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const LOADING_ARTIST = 'LOADING_ARTIST';
export const LOADING_FINISH = 'LOADING_FINISH';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';

export const LOAD_USER = 'LOAD_USER';
export const UPLOAD_USER = 'UPLOAD_USER';
export const UPLOAD_USER_ERROR = 'UPLOAD_USER_ERROR';

export const LOAD_USER_ALBUMS = 'LOAD_USER_ALBUMS';
export const UPLOAD_ALBUM = 'UPLOAD_ALBUM';
export const UPLOAD_ALBUM_ERROR = 'UPLOAD_ALBUM_ERROR';
export const UPLOAD_ALBUM_IMAGE = 'UPLOAD_ALBUM_IMAGE';
export const UPLOAD_ALBUM_IMAGE_ERROR = 'UPLOAD_ALBUM_IMAGE_ERROR';
export const LOAD_ALL_ALBUMS = 'LOAD_ALL_ALBUMS';
export const LOAD_ALL_ALBUMS_ERROR = 'LOAD_ALL_ALBUMS_ERROR';

export const LOAD_ALL_ARTISTS = 'LOAD_ALL_ARTISTS';
export const LOAD_ALL_ARTISTS_ERROR = 'LOAD_ALL_ARTISTS_ERROR';
export const LOAD_ARTIST_ALBUMS = 'LOAD_ARTIST_ALBUMS';
